meshMaker: use getNumber instead of get_number
The Gmsh reference manual documents gmsh.option.getNumber.[1] The
get_number method is an alias added to the Python and Julia APIs,[2] and
available since Gmsh 4.8.0.[3] Debian bullseye ships python3-gmsh 4.7.1,
which does not provided this alias, and has full_test.py fail with:

    AttributeError: type object 'option' has no attribute 'get_number'

Use the documented method name, which works on all the Gmsh versions we
support.

[1] https://gmsh.info/doc/texinfo/gmsh.html#index-gmsh_002foption_002fgetNumber
[2] https://gitlab.onelab.info/gmsh/gmsh/-/commit/85167a133d9
[3] https://gitlab.onelab.info/gmsh/gmsh/-/releases/gmsh_4_8_0