Accept meshes with no surface elements
Now that feeLLGood adds the missing surface regions, a user can
legitimately provide a mesh with no surface elements at all. With
such a mesh, however, feeLLGood fails with:

    Fatal Error: mesh file contains other 2D elements than triangles.

This is because it expects the mesh to have exactly one type of surface
elements, namely triangles.

Let us also accept meshes with zero types of surface elements.