Fix build with Eigen < 3.4.0
Commit e570ac4 (Mesh::updateNodes() only update nodes...) introduced
code conditionally built when the Eigen version is prior to 3.4.0. This
code fails with:

    error: ‘sq’ was not declared in this scope;
    did you mean ‘Nodes::sq’?

Fix this error and, while we are at it, also the following warning:

    warning: comparison of integer expressions of different signedness:
    ‘unsigned int’ and ‘const int’